# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 075c30dfa69ae87f983d9ca0dd7cd8ad56e8b7fea140e362a36f2c335dc15db7abc6bc46758f7133f7a241833ea7ba9fde255e51d7078eaca21f4433988ab4a4

test:
  secret_key_base: 3f27f10c925ec31bac5c5c0fae252bb90c9be9cef7ac617d46ce932359fdccbee2165f5c706e4602c5068a4219fdd1fca2630f72431bcfc012b04bcb103a27f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
